apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.label }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
